const voices = (() => {
  //prettier-ignore
  const voices = [
    { "code": "af", "name": "Afrikaans" },
    { "code": "ar", "name": "Arabic" },
    { "code": "bg", "name": "Bulgarian" },
    { "code": "bn", "name": "Bengali" },
    { "code": "bs", "name": "Bosnian" },
    { "code": "ca", "name": "Catalan" },
    { "code": "cs", "name": "Czech" },
    { "code": "da", "name": "Danish" },
    { "code": "de", "name": "German" },
    { "code": "el", "name": "Greek" },
    { "code": "en", "name": "English" },
    { "code": "es", "name": "Spanish" },
    { "code": "et", "name": "Estonian" },
    { "code": "fi", "name": "Finnish" },
    { "code": "fr", "name": "French" },
    { "code": "gu", "name": "Gujarati" },
    { "code": "hi", "name": "Hindi" },
    { "code": "hr", "name": "Croatian" },
    { "code": "hu", "name": "Hungarian" },
    { "code": "id", "name": "Indonesian" },
    { "code": "is", "name": "Icelandic" },
    { "code": "it", "name": "Italian" },
    { "code": "iw", "name": "Hebrew" },
    { "code": "ja", "name": "Japanese" },
    { "code": "jw", "name": "Javanese" },
    { "code": "km", "name": "Khmer" },
    { "code": "kn", "name": "Kannada" },
    { "code": "ko", "name": "Korean" },
    { "code": "la", "name": "Latin" },
    { "code": "lv", "name": "Latvian" },
    { "code": "ml", "name": "Malayalam" },
    { "code": "mr", "name": "Marathi" },
    { "code": "ms", "name": "Malay" },
    { "code": "my", "name": "Myanmar (Burmese)" },
    { "code": "ne", "name": "Nepali" },
    { "code": "nl", "name": "Dutch" },
    { "code": "no", "name": "Norwegian" },
    { "code": "pl", "name": "Polish" },
    { "code": "pt", "name": "Portuguese" },
    { "code": "ro", "name": "Romanian" },
    { "code": "ru", "name": "Russian" },
    { "code": "si", "name": "Sinhala" },
    { "code": "sk", "name": "Slovak" },
    { "code": "sq", "name": "Albanian" },
    { "code": "sr", "name": "Serbian" },
    { "code": "su", "name": "Sundanese" },
    { "code": "sv", "name": "Swedish" },
    { "code": "sw", "name": "Swahili" },
    { "code": "ta", "name": "Tamil" },
    { "code": "te", "name": "Telugu" },
    { "code": "th", "name": "Thai" },
    { "code": "tl", "name": "Filipino" },
    { "code": "tr", "name": "Turkish" },
    { "code": "uk", "name": "Ukrainian" },
    { "code": "ur", "name": "Urdu" },
    { "code": "vi", "name": "Vietnamese" },
    { "code": "zh", "name": "Chinese" },
  ]

  const accents = [
    { "tld": "com", "accent": "Global/Neutral" },
    { "tld": "ad", "accent": "Andorra" },
    { "tld": "ae", "accent": "United Arab Emirates" },
    { "tld": "com.af", "accent": "Afghanistan" },
    { "tld": "com.ag", "accent": "Antigua and Barbuda" },
    { "tld": "com.ai", "accent": "Anguilla" },
    { "tld": "com.ar", "accent": "Argentina" },
    { "tld": "as", "accent": "American Samoa" },
    { "tld": "at", "accent": "Austria" },
    { "tld": "com.au", "accent": "Australia" },
    { "tld": "az", "accent": "Azerbaijan" },
    { "tld": "ba", "accent": "Bosnia and Herzegovina" },
    { "tld": "com.bd", "accent": "Bangladesh" },
    { "tld": "be", "accent": "Belgium" },
    { "tld": "bf", "accent": "Burkina Faso" },
    { "tld": "bg", "accent": "Bulgaria" },
    { "tld": "bj", "accent": "Benin" },
    { "tld": "br", "accent": "Brazil" },
    { "tld": "bs", "accent": "Bahamas" },
    { "tld": "bt", "accent": "Bhutan" },
    { "tld": "co.bw", "accent": "Botswana" },
    { "tld": "by", "accent": "Belarus" },
    { "tld": "com.bz", "accent": "Belize" },
    { "tld": "ca", "accent": "Canada" },
    { "tld": "cd", "accent": "Democratic Republic of the Congo" },
    { "tld": "ch", "accent": "Switzerland" },
    { "tld": "ci", "accent": "Côte d'Ivoire" },
    { "tld": "co.ck", "accent": "Cook Islands" },
    { "tld": "cl", "accent": "Chile" },
    { "tld": "cm", "accent": "Cameroon" },
    { "tld": "cn", "accent": "China" },
    { "tld": "com.co", "accent": "Colombia" },
    { "tld": "co.cr", "accent": "Costa Rica" },
    { "tld": "cv", "accent": "Cape Verde" },
    { "tld": "dj", "accent": "Djibouti" },
    { "tld": "dm", "accent": "Dominica" },
    { "tld": "com.do", "accent": "Dominican Republic" },
    { "tld": "dz", "accent": "Algeria" },
    { "tld": "com.ec", "accent": "Ecuador" },
    { "tld": "ee", "accent": "Estonia" },
    { "tld": "com.eg", "accent": "Egypt" },
    { "tld": "es", "accent": "Spain" },
    { "tld": "et", "accent": "Ethiopia" },
    { "tld": "fi", "accent": "Finland" },
    { "tld": "com.fj", "accent": "Fiji" },
    { "tld": "fm", "accent": "Micronesia" },
    { "tld": "fr", "accent": "France" },
    { "tld": "ga", "accent": "Gabon" },
    { "tld": "ge", "accent": "Georgia" },
    { "tld": "gg", "accent": "Guernsey" },
    { "tld": "com.gh", "accent": "Ghana" },
    { "tld": "com.gi", "accent": "Gibraltar" },
    { "tld": "gl", "accent": "Greenland" },
    { "tld": "gm", "accent": "Gambia" },
    { "tld": "gr", "accent": "Greece" },
    { "tld": "com.gt", "accent": "Guatemala" },
    { "tld": "gy", "accent": "Guyana" },
    { "tld": "com.hk", "accent": "Hong Kong" },
    { "tld": "hn", "accent": "Honduras" },
    { "tld": "ht", "accent": "Haiti" },
    { "tld": "hr", "accent": "Croatia" },
    { "tld": "hu", "accent": "Hungary" },
    { "tld": "co.id", "accent": "Indonesia" },
    { "tld": "ie", "accent": "Ireland" },
    { "tld": "co.il", "accent": "Israel" },
    { "tld": "im", "accent": "Isle of Man" },
    { "tld": "co.in", "accent": "India" },
    { "tld": "iq", "accent": "Iraq" },
    { "tld": "is", "accent": "Iceland" },
    { "tld": "it", "accent": "Italy" },
    { "tld": "iw", "accent": "Hebrew" },
    { "tld": "je", "accent": "Jersey" },
    { "tld": "com.je", "accent": "Jersey" },
    { "tld": "jo", "accent": "Jordan" },
    { "tld": "co.jp", "accent": "Japan" },
    { "tld": "co.ke", "accent": "Kenya" },
    { "tld": "com.kh", "accent": "Cambodia" },
    { "tld": "ki", "accent": "Kiribati" },
    { "tld": "kg", "accent": "Kyrgyzstan" },
    { "tld": "co.kr", "accent": "South Korea" },
    { "tld": "com.kw", "accent": "Kuwait" },
    { "tld": "kz", "accent": "Kazakhstan" },
    { "tld": "la", "accent": "Laos" },
    { "tld": "com.lb", "accent": "Lebanon" },
    { "tld": "li", "accent": "Liechtenstein" },
    { "tld": "lk", "accent": "Sri Lanka" },
    { "tld": "co.ls", "accent": "Lesotho" },
    { "tld": "lu", "accent": "Luxembourg" },
    { "tld": "lv", "accent": "Latvia" },
    { "tld": "com.ly", "accent": "Libya" },
    { "tld": "com.ma", "accent": "Morocco" },
    { "tld": "md", "accent": "Moldova" },
    { "tld": "me", "accent": "Montenegro" },
    { "tld": "mg", "accent": "Madagascar" },
    { "tld": "mk", "accent": "North Macedonia" },
    { "tld": "ml", "accent": "Mali" },
    { "tld": "mm", "accent": "Myanmar" },
    { "tld": "mn", "accent": "Mongolia" },
    { "tld": "ms", "accent": "Montserrat" },
    { "tld": "com.mt", "accent": "Malta" },
    { "tld": "mu", "accent": "Mauritius" },
    { "tld": "mv", "accent": "Maldives" },
    { "tld": "mw", "accent": "Malawi" },
    { "tld": "com.mx", "accent": "Mexico" },
    { "tld": "com.my", "accent": "Malaysia" },
    { "tld": "co.mz", "accent": "Mozambique" },
    { "tld": "na", "accent": "Namibia" },
    { "tld": "ng", "accent": "Nigeria" },
    { "tld": "ni", "accent": "Nicaragua" },
    { "tld": "ne", "accent": "Niger" },
    { "tld": "nl", "accent": "Netherlands" },
    { "tld": "no", "accent": "Norway" },
    { "tld": "com.np", "accent": "Nepal" },
    { "tld": "nr", "accent": "Nauru" },
    { "tld": "nu", "accent": "Niue" },
    { "tld": "co.nz", "accent": "New Zealand" },
    { "tld": "com.om", "accent": "Oman" },
    { "tld": "pa", "accent": "Panama" },
    { "tld": "pe", "accent": "Peru" },
    { "tld": "pg", "accent": "Papua New Guinea" },
    { "tld": "ph", "accent": "Philippines" },
    { "tld": "pk", "accent": "Pakistan" },
    { "tld": "pl", "accent": "Poland" },
    { "tld": "pn", "accent": "Pitcairn Islands" },
    { "tld": "com.pr", "accent": "Puerto Rico" },
    { "tld": "ps", "accent": "Palestine" },
    { "tld": "pt", "accent": "Portugal" },
    { "tld": "com.py", "accent": "Paraguay" },
    { "tld": "com.qa", "accent": "Qatar" },
    { "tld": "ro", "accent": "Romania" },
    { "tld": "ru", "accent": "Russia" },
    { "tld": "rw", "accent": "Rwanda" },
    { "tld": "com.sa", "accent": "Saudi Arabia" },
    { "tld": "com.sb", "accent": "Solomon Islands" },
    { "tld": "sc", "accent": "Seychelles" },
    { "tld": "se", "accent": "Sweden" },
    { "tld": "com.sg", "accent": "Singapore" },
    { "tld": "sh", "accent": "Saint Helena" },
    { "tld": "si", "accent": "Slovenia" },
    { "tld": "sk", "accent": "Slovakia" },
    { "tld": "com.sl", "accent": "Sierra Leone" },
    { "tld": "sn", "accent": "Senegal" },
    { "tld": "so", "accent": "Somalia" },
    { "tld": "sm", "accent": "San Marino" },
    { "tld": "sr", "accent": "Suriname" },
    { "tld": "lu", "accent": "Luxembourg" },
    { "tld": "lv", "accent": "Latvia" },
    { "tld": "com.ly", "accent": "Libya" },
    { "tld": "com.ma", "accent": "Morocco" },
    { "tld": "md", "accent": "Moldova" },
    { "tld": "me", "accent": "Montenegro" },
    { "tld": "mg", "accent": "Madagascar" },
    { "tld": "mk", "accent": "North Macedonia" },
    { "tld": "ml", "accent": "Mali" },
    { "tld": "mm", "accent": "Myanmar" },
    { "tld": "mn", "accent": "Mongolia" },
    { "tld": "ms", "accent": "Montserrat" },
    { "tld": "com.mt", "accent": "Malta" },
    { "tld": "mu", "accent": "Mauritius" },
    { "tld": "mv", "accent": "Maldives" },
    { "tld": "mw", "accent": "Malawi" },
    { "tld": "com.mx", "accent": "Mexico" },
    { "tld": "com.my", "accent": "Malaysia" },
    { "tld": "co.mz", "accent": "Mozambique" },
    { "tld": "na", "accent": "Namibia" },
    { "tld": "ng", "accent": "Nigeria" },
    { "tld": "ni", "accent": "Nicaragua" },
    { "tld": "ne", "accent": "Niger" },
    { "tld": "nl", "accent": "Netherlands" },
    { "tld": "no", "accent": "Norway" },
    { "tld": "com.np", "accent": "Nepal" },
    { "tld": "nr", "accent": "Nauru" },
    { "tld": "nu", "accent": "Niue" },
    { "tld": "co.nz", "accent": "New Zealand" },
    { "tld": "com.om", "accent": "Oman" },
    { "tld": "pa", "accent": "Panama" },
    { "tld": "pe", "accent": "Peru" },
    { "tld": "pg", "accent": "Papua New Guinea" },
    { "tld": "ph", "accent": "Philippines" },
    { "tld": "pk", "accent": "Pakistan" },
    { "tld": "pl", "accent": "Poland" },
    { "tld": "pn", "accent": "Pitcairn Islands" },
    { "tld": "com.pr", "accent": "Puerto Rico" },
    { "tld": "ps", "accent": "Palestine" },
    { "tld": "pt", "accent": "Portugal" },
    { "tld": "com.py", "accent": "Paraguay" },
    { "tld": "com.qa", "accent": "Qatar" },
    { "tld": "ro", "accent": "Romania" },
    { "tld": "ru", "accent": "Russia" },
    { "tld": "rw", "accent": "Rwanda" },
    { "tld": "com.sa", "accent": "Saudi Arabia" },
    { "tld": "com.sb", "accent": "Solomon Islands" },
    { "tld": "sc", "accent": "Seychelles" },
    { "tld": "se", "accent": "Sweden" },
    { "tld": "com.sg", "accent": "Singapore" },
    { "tld": "sh", "accent": "Saint Helena" },
    { "tld": "si", "accent": "Slovenia" },
    { "tld": "sk", "accent": "Slovakia" },
    { "tld": "com.sl", "accent": "Sierra Leone" },
    { "tld": "sn", "accent": "Senegal" },
    { "tld": "so", "accent": "Somalia" },
    { "tld": "sm", "accent": "San Marino" },
    { "tld": "sr", "accent": "Suriname" },
    { "tld": "st", "accent": "São Tomé and Príncipe" },
    { "tld": "com.sv", "accent": "El Salvador" },
    { "tld": "td", "accent": "Chad" },
    { "tld": "tg", "accent": "Togo" },
    { "tld": "co.th", "accent": "Thailand" },
    { "tld": "com.tj", "accent": "Tajikistan" },
    { "tld": "tl", "accent": "Timor-Leste" },
    { "tld": "tm", "accent": "Turkmenistan" },
    { "tld": "tn", "accent": "Tunisia" },
    { "tld": "to", "accent": "Tonga" },
    { "tld": "com.tr", "accent": "Turkey" },
    { "tld": "tt", "accent": "Trinidad and Tobago" },
    { "tld": "com.tw", "accent": "Taiwan" },
    { "tld": "co.tz", "accent": "Tanzania" },
    { "tld": "com.ua", "accent": "Ukraine" },
    { "tld": "co.ug", "accent": "Uganda" },
    { "tld": "co.uk", "accent": "United Kingdom" },
    { "tld": "com.uy", "accent": "Uruguay" },
    { "tld": "co.uz", "accent": "Uzbekistan" },
    { "tld": "com.vc", "accent": "Saint Vincent and the Grenadines" },
    { "tld": "co.ve", "accent": "Venezuela" },
    { "tld": "vg", "accent": "British Virgin Islands" },
    { "tld": "co.vi", "accent": "U.S. Virgin Islands" },
    { "tld": "com.vn", "accent": "Vietnam" },
    { "tld": "vu", "accent": "Vanuatu" },
    { "tld": "ws", "accent": "Samoa" },
    { "tld": "rs", "accent": "Serbia" },
    { "tld": "co.za", "accent": "South Africa" },
    { "tld": "co.zm", "accent": "Zambia" },
    { "tld": "co.zw", "accent": "Zimbabwe" },
    { "tld": "cat", "accent": "Catalan Language/Culture" }
  ]

  function findVoiceByCode(code) {
    return voices.find((l) => l.code === code);
  }

  function findVoiceByName(name) {
    return voices.find((l) => l.name === name);
  }

  function findAccentByCode(tld) {
    return accents.find((l) => l.tld === tld);
  }

  function findAccentByName(name) {
    return accents.find((l) => l.name === name);
  }

  voices.findVoiceByCode = findVoiceByCode.bind(voices);
  voices.findVoiceByName = findVoiceByName.bind(voices);
  voices.findAccentByCode = findAccentByCode.bind(voices);
  voices.findAccentByName = findAccentByName.bind(voices);

  return {
    voices,
    accents,
  };
})();

module.exports = voices;
